

const Table = [
    {
        "id": 1,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 2,
        "Date": "04/4/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 3,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 4,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 5,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 6,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 7,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 8,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 9,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 10,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 11,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },
    {
        "id": 12,
        "Date": "02/01/2022",
        "FirstName": "John",
        "LastName": "Akinbade",
        "Email Address": "john@gmail.com",
        "Subject": "Laundry",
        "Action": "•",
    },

]


export default Table;